import { useNavigate } from 'react-router-dom';
import { FaImage, FaMagic, FaArrowRight, FaRobot, FaLightbulb, FaCog } from 'react-icons/fa';

const FeatureCard = ({ icon: Icon, title, description, color }) => (
  <div className="bg-white/10 backdrop-blur-sm p-6 rounded-2xl border border-white/20 hover:border-white/40 transition-all hover:shadow-xl hover:-translate-y-1">
    <div className={`w-12 h-12 ${color} rounded-xl flex items-center justify-center mb-4`}>
      <Icon className="text-white text-xl" />
    </div>
    <h3 className="text-xl font-bold text-white mb-2">{title}</h3>
    <p className="text-gray-300">{description}</p>
  </div>
);

export default function LandingPage() {
  const navigate = useNavigate();

  const features = [
    {
      icon: FaImage,
      title: 'Image to Text',
      description: 'Upload any image and get an accurate, detailed description generated by AI.',
      color: 'bg-blue-500',
      path: '/image-to-text'
    },
    {
      icon: FaMagic,
      title: 'Text to Image',
      description: 'Turn your ideas into stunning visuals with our powerful AI image generation.',
      color: 'bg-purple-500',
      path: '/text-to-image'
    },
    {
      icon: FaRobot,
      title: 'AI-Powered',
      description: 'Leveraging state-of-the-art AI models for the best results.',
      color: 'bg-pink-500'
    },
    {
      icon: FaCog,
      title: 'Easy to Use',
      description: 'Simple, intuitive interface that makes AI accessible to everyone.',
      color: 'bg-indigo-500'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 text-white overflow-hidden">
      {/* Hero Section */}
      <div className="relative pt-32 pb-20 px-4 sm:px-6 lg:pt-40 lg:pb-28 lg:px-8">
        <div className="relative max-w-7xl mx-auto">
          <div className="text-center">
            <h1 className="text-4xl tracking-tight font-extrabold text-white sm:text-5xl md:text-6xl">
              <span className="block">Transform Your Ideas</span>
              <span className="block text-transparent bg-clip-text bg-gradient-to-r from-yellow-400 to-pink-500">
                With AI-Powered Media
              </span>
            </h1>
            <p className="mt-3 max-w-md mx-auto text-base text-gray-300 sm:text-lg md:mt-5 md:text-xl md:max-w-3xl">
              Create stunning visuals from text or generate accurate descriptions from images using cutting-edge AI technology.
              Fast, easy, and incredibly powerful.
            </p>
            <div className="mt-10 flex flex-col sm:flex-row justify-center gap-4">
              <button
                onClick={() => navigate('/image-to-text')}
                className="flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-full text-white bg-blue-600 hover:bg-blue-700 md:py-4 md:text-lg md:px-10 transition-all hover:scale-105"
              >
                <FaImage className="mr-2" /> Image to Text
              </button>
              <button
                onClick={() => navigate('/text-to-image')}
                className="flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-full text-white bg-pink-600 hover:bg-pink-700 md:py-4 md:text-lg md:px-10 transition-all hover:scale-105"
              >
                <FaMagic className="mr-2" /> Text to Image
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Features Section */}
      <div className="relative py-12 bg-gradient-to-b from-slate-900 to-slate-800">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-extrabold text-white sm:text-4xl">
              Powerful Features
            </h2>
            <p className="mt-3 max-w-2xl mx-auto text-xl text-gray-300 sm:mt-4">
              Everything you need to bring your creative vision to life
            </p>
          </div>

          <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {features.map((feature, index) => (
              <div 
                key={index} 
                onClick={() => feature.path && navigate(feature.path)}
                className={`${feature.path ? 'cursor-pointer hover:shadow-2xl' : ''}`}
              >
                <FeatureCard
                  icon={feature.icon}
                  title={feature.title}
                  description={feature.description}
                  color={feature.color}
                />
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* CTA Section */}
      <div className="relative bg-gradient-to-r from-blue-600 to-indigo-600 overflow-hidden">
        <div className="relative pt-12 pb-16 px-4 sm:pt-16 sm:px-6 lg:px-8 lg:max-w-7xl lg:mx-auto lg:grid lg:grid-cols-2 lg:pt-24">
          <div className="lg:col-start-1 lg:pl-8 lg:pr-8">
            <h2 className="text-3xl font-extrabold text-white sm:text-4xl">
              <span className="block">Ready to get started?</span>
              <span className="block text-blue-100">Try it out now for free.</span>
            </h2>
            <p className="mt-4 text-lg text-blue-100">
              No credit card required. Experience the power of AI media generation today.
            </p>
            <div className="mt-8 flex flex-col sm:flex-row space-y-3 sm:space-y-0 sm:space-x-4">
              <button
                onClick={() => navigate('/text-to-image')}
                className="flex items-center justify-center px-6 py-3 border border-transparent text-base font-medium rounded-md text-blue-700 bg-white hover:bg-blue-50 md:py-4 md:text-lg md:px-8 transition-all hover:scale-105"
              >
                Generate Your First Image <FaArrowRight className="ml-2" />
              </button>
            </div>
          </div>
          <div className="mt-12 lg:mt-0 lg:col-start-2 lg:pl-8">
            <div className="bg-white/10 backdrop-blur-sm p-6 rounded-2xl border border-white/20">
              <div className="aspect-w-16 aspect-h-9 rounded-lg overflow-hidden">
                <div className="h-64 bg-gradient-to-br from-blue-400 to-indigo-600 rounded-lg flex items-center justify-center">
                  <FaLightbulb className="text-white text-6xl opacity-50" />
                </div>
              </div>
              <div className="mt-4 text-center">
                <p className="text-white text-lg font-medium">
                  "A picture is worth a thousand words. Let AI help you find them."
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer Note */}
      <footer className="bg-slate-900">
        <div className="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
          <p className="text-center text-sm text-gray-500">
            &copy; {new Date().getFullYear()} AI Media. All rights reserved. Powered by advanced AI technology.
          </p>
        </div>
      </footer>
    </div>
  );
}
